# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e764d1dcf742139793f86f7713f67507498ed7cae944b4af278ac706ca372535042388919c747a4eb5f038d96675fff2f356f7055f3204ac5fae93290ffcc58

test:
  secret_key_base: 6488c9d1b0fa1af80544a840b8b38877b41c0cedc52295fa7f7d4ceb6b7fc2634e56a7b8d3d7fff7256c3c40127cf8387855b09102440e195a4d4f8a239e810b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
